version: "2"
services:
  tomcat-systemd:
    build: "./tomcat-systemd"
    image: "tomcat-systemd"
  web:
    build: "./web"
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./cache-web/logs:/var/lib/tomcats/web/logs"
      - "./cache-web/work:/var/lib/tomcats/web/work"
      - "./cache-web/temp:/var/lib/tomcats/web/temp"
    ports:
      - "8080:8080"
